name: Test

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.7.7' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rake default task
      run: |
        bundle install --jobs=3 --retry=3
        bundle exec rake
